### PR TITLE
Changes for HW Inc and Navbar

### PR DESCRIPTION
**Pull request by jononon**
Would be nice to have before Junior class meeting on Tues.

Thanks!

### CODE REVIEW

**Comment by arianais** [comment]
sorry missed these. is there anything for me to do?

**Comment by jononon** [comment]
No - I'll pull these on the server. Thanks so much!

**Comment by jononon** [comment]
Live site now reflects those changes. Thanks!

**Comment by arianais** [comment]
No problem! Thanks

**Pull request merged**
